//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagerService.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventManagerService.Properties.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Booking {0} confirmed successfully.
        /// </summary>
        internal static string BookingConfirmed {
            get {
                return ResourceManager.GetString("BookingConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Booking {0} not found when processing.
        /// </summary>
        internal static string BookingNotFoundWhenProcessing {
            get {
                return ResourceManager.GetString("BookingNotFoundWhenProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Booking {0} not found when attempting to release resources.
        /// </summary>
        internal static string BookingNotFoundWhenReleasing {
            get {
                return ResourceManager.GetString("BookingNotFoundWhenReleasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Booking {0} processing cancelled.
        /// </summary>
        internal static string BookingProcessingCancelled {
            get {
                return ResourceManager.GetString("BookingProcessingCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error processing booking {0}. Rejecting and releasing seats.
        /// </summary>
        internal static string BookingProcessingErrorRejecting {
            get {
                return ResourceManager.GetString("BookingProcessingErrorRejecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error in BookingBackgroundService.
        /// </summary>
        internal static string ErrorInBookingBackgroundService {
            get {
                return ResourceManager.GetString("ErrorInBookingBackgroundService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event {0} not found. Booking {1} rejected..
        /// </summary>
        internal static string EventNotFoundBookingRejected {
            get {
                return ResourceManager.GetString("EventNotFoundBookingRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to release resources for booking {0}.
        /// </summary>
        internal static string FailedToReleaseResources {
            get {
                return ResourceManager.GetString("FailedToReleaseResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {firstParamName} ({firstParamValue}) must be greater than {secondParamName} ({SecondParamName}).
        /// </summary>
        internal static string GreaterThanValidationError {
            get {
                return ResourceManager.GetString("GreaterThanValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No available seats for this event.
        /// </summary>
        internal static string NoAvailableSeatsError {
            get {
                return ResourceManager.GetString("NoAvailableSeatsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This attribute can only be used on comparable types.
        /// </summary>
        internal static string NoComparableError {
            get {
                return ResourceManager.GetString("NoComparableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The object with the specified identifier {0} was not found..
        /// </summary>
        internal static string ObjectNotFound {
            get {
                return ResourceManager.GetString("ObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Page number must be greater then  0. Current page number is {0}.
        /// </summary>
        internal static string PageNumberException {
            get {
                return ResourceManager.GetString("PageNumberException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Page size must be greater then or equal to 10 and less then or equal to 100. Current page size is {0}.
        /// </summary>
        internal static string PageSizeException {
            get {
                return ResourceManager.GetString("PageSizeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The field {0} must be a string with a minimum length of {1} and a maximum length of {2}.
        /// </summary>
        internal static string StringLengthError {
            get {
                return ResourceManager.GetString("StringLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This attribute can be only positive. Current value is {0}.
        /// </summary>
        internal static string TotalSeatsValidationError {
            get {
                return ResourceManager.GetString("TotalSeatsValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It is not possible to change the status of a completed booking..
        /// </summary>
        internal static string TryChangeCompletedBookingError {
            get {
                return ResourceManager.GetString("TryChangeCompletedBookingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unhandled exception. Method={Method}, Path={Path}, RequestId={RequestId}.
        /// </summary>
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown property {0}.
        /// </summary>
        internal static string UnknownPropertyError {
            get {
                return ResourceManager.GetString("UnknownPropertyError", resourceCulture);
            }
        }
    }
}
